import os
import uuid
import asyncio
from typing import Dict, Any

class WorkspaceManager:
    """
    yAI Omni-Intelligence Blueprint: Pillar 1 (Autonomous Execution)
    Replaces basic local subprocesses with isolated, async "WebContainer" style workspaces.
    Inspired by OpenHands, OpenDevin, and bolt.new.
    """
    def __init__(self, base_dir: str = "./workspaces"):
        self.base_dir = base_dir
        self.active_workspaces: Dict[str, Any] = {}
        os.makedirs(self.base_dir, exist_ok=True)
        
    async def provision_workspace(self, project_name: str) -> str:
        """
        Provisions a new isolated workspace container for the AI Swarm.
        Returns the unique Workspace ID.
        """
        workspace_id = str(uuid.uuid4())[:8]
        workspace_path = os.path.join(self.base_dir, f"{project_name}_{workspace_id}")
        os.makedirs(workspace_path, exist_ok=True)
        
        # In a full deployment, this would initialize a Docker container or WebContainer API
        self.active_workspaces[workspace_id] = {
            "path": workspace_path,
            "status": "ready",
            "processes": []
        }
        print(f"[WorkspaceManager] Provisioned isolated WebContainer-style workspace at {workspace_path}")
        return workspace_id
        
    async def write_file(self, workspace_id: str, file_path: str, content: str) -> bool:
        """Securely writes a file generated by the Coder into the physical workspace."""
        if workspace_id not in self.active_workspaces:
            return False
            
        workspace = self.active_workspaces[workspace_id]
        full_path = os.path.join(workspace["path"], file_path)
        
        # Ensure directories exist
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        
        try:
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"[WorkspaceManager] Physically wrote {file_path} into {workspace_id}")
            return True
        except Exception as e:
            print(f"[WorkspaceManager] File Write Error: {e}")
            return False

    async def execute_in_workspace(self, workspace_id: str, command: str) -> str:
        """
        Executes a command asynchronously inside the isolated workspace using blink-style multiplexing.
        """
        if workspace_id not in self.active_workspaces:
            return "Error: Workspace not found."
            
        workspace = self.active_workspaces[workspace_id]
        workspace_path = workspace["path"]
        
        print(f"[WorkspaceManager] Executing in {workspace_id}: {command}")
        
        try:
            # We use asyncio.create_subprocess_shell to multiplex concurrent terminal commands
            process = await asyncio.create_subprocess_shell(
                command,
                cwd=workspace_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            # Register the process so the Swarm can monitor it
            workspace["processes"].append(process)
            
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0:
                return stdout.decode().strip()
            else:
                return f"Error: {stderr.decode().strip()}"
                
        except Exception as e:
            return f"Execution Exception: {str(e)}"
            
    async def execute_with_healing(self, workspace_id: str, command: str, max_retries: int = 2) -> str:
        """
        Omni-Intelligence Auto-Healing Loop (Inspired by OpenHands & Cursor).
        If a command fails, routes the stderr back to the LLM to write a patch command automatically.
        """
        for attempt in range(max_retries):
            result = await self.execute_in_workspace(workspace_id, command)
            if not result.startswith("Error:"):
                return result
                
            print(f"[Auto-Heal] Attempt {attempt+1}: Command '{command}' failed. Triggering Agentic Healing...")
            
            try:
                from backend.agents.router import ModelRouter
                healer = ModelRouter.get_optimal_llm("ArchitectAgent", complexity="coding")
                
                heal_prompt = f"""You are the yAI Auto-Healing Agent.
The user tried to run: `{command}`
But it failed with this error:
{result}

Provide EXACTLY ONE terminal command to run to fix this issue (e.g. installing a missing dependency via npm or pip, or fixing a file).
DO NOT wrap the command in markdown blocks. Output only the raw command string."""
                
                heal_response = await healer.ainvoke(heal_prompt)
                fix_command = heal_response.content.strip()
                # strip backticks if any
                if fix_command.startswith("`") and fix_command.endswith("`"):
                    fix_command = fix_command.replace("`", "").strip()
                    
                print(f"[Auto-Heal] Agent proposed fix: {fix_command}")
                await self.execute_in_workspace(workspace_id, fix_command)
                
            except Exception as e:
                print(f"[Auto-Heal] Agentic healing failed: {e}")
                
        return await self.execute_in_workspace(workspace_id, command)

    def list_workspaces(self) -> Dict[str, Any]:
        return self.active_workspaces

# Standalone Test for Pillar 1
if __name__ == "__main__":
    async def run_test():
        manager = WorkspaceManager()
        print("Booting yAI Autonomous Workspace Manager...")
        
        # Simulate Swarm requesting a workspace for a new Next.js app
        ws_id = await manager.provision_workspace("nextjs_SaaS")
        
        # Simulate blink-style fast execution: initializing a project instantly
        print("\nSimulating agentic command execution...")
        result_1 = await manager.execute_in_workspace(ws_id, "echo '{\"name\": \"gstack-app\"}' > package.json")
        result_2 = await manager.execute_in_workspace(ws_id, "mkdir src && echo 'console.log(\"Omni-Intelligence Active\");' > src/index.js")
        
        # Verify files were created
        verify = await manager.execute_in_workspace(ws_id, "dir" if os.name == "nt" else "ls -la")
        print(f"\nWorkspace Contents:\n{verify}")
        print("\n[WorkspaceManager] Test Complete. Containers isolated successfully.")
        
    asyncio.run(run_test())
